### PR TITLE
Remove direction

### PR DESCRIPTION
**Pull request by nopparuj917**
Get this fking useless feature out asap. This shit cost too much, it's like getting rob.

### CODE REVIEW

**Comment by nopparuj917** [comment]
@noppakorn merge hnoi

**Comment by nopparuj917** [comment]
@noppakorn merge hnoi

**Comment by noppakorn** [comment]
Yeah right, that's what you get for doing things that are not required. @nnanthicha come see this.

**Comment by noppakorn** [comment]
Yeah right, that's what you get for doing things that are not required. @nnanthicha come see this.

**Review by noppakorn — APPROVED** [review]

**Pull request merged**
